version: '3'
tasks:
  runlocal:
    aliases:
      - run
    desc: runs cmd/main.go with all flags
    cmd: go run cmd/main.go --CONFIG_PATH=./configs/local.json
  runprod:
    desc: runs cmd/main.go with all flags for prod
    cmd: go run cmd/main.go --CONFIG_PATH=./configs/prod.json
  runenv:
    desc: runs cmd/main.go with config file in env
    cmd: go run cmd/main.go